#!/usr/bin/bash

swww query || swww-daemon --format xrgb &
swww img "$1" --transition-fps 60 --transition-type grow --transition-bezier .43,1.19,1,.4 --transition-pos 0.925,0.977 --transition-duration 1
